### ISSUE TITLE
Cambios solicitados

### ISSUE THREAD

**Issue by CarlosRubioTNM** [CrlsMt/PracticaEquipoBubbaloo#1]
Buen trabajo, jóvenes.

Ahora les voy a pedir que realicen los siguientes cambios:

1. Arreglen el enlace a la imagen de Anais y los errores de ortografía.
2. Modifiquen la página para que las listas tengan un elemento por línea.
3. Agreguen la Misión y Visión (inventadas) de la empresa.

Cuando terminen, respondan por este medio para revisar los cambios. Saludos.

**Comment by CrlsMt** [comment]
Cambios listos

**Comment by CarlosRubioTNM** [comment]
Excelente, jóvenes. Cierro el issue. 👍
